/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */


#ifndef __BMP_LOGO_H__
#define __BMP_LOGO_H__

#define BMP_LOGO_WIDTH		364
#define BMP_LOGO_HEIGHT		128
#define BMP_LOGO_COLORS		23
#define BMP_LOGO_OFFSET		16

extern unsigned short bmp_logo_palette[];
extern unsigned char bmp_logo_bitmap[];

#endif /* __BMP_LOGO_H__ */
